#1 Should add JavaDoc for public and protected methods and fields
zalando-incubator/aws-support-spring-boot-starter pull request #3
Opened 2017-01-06 07:22 UTC by duergner

Nothing more than already written on the subject - simply adding JavaDoc to public and protected members

2017-01-06 09:30 UTC, jbellmann commented on src/main/java/org/zalando/automata/aws/AwsEnvironmentPostProcessor.java
>     */
Missing spaces here, and some more below. Can you fix this please?

2017-01-06 09:33 UTC, jbellmann requested changes
Well done. I added a comment regarding spaces for javadocs.

2017-01-06 12:36 UTC, duergner commented on src/main/java/org/zalando/automata/aws/AwsEnvironmentPostProcessor.java
>     */
What would you change here? This one should have two spaces as recommended by http://blog.joda.org/2012/11/javadoc-coding-standards.html

I added the missing double spaces on the return statement below (and changed both param and return to start lower case

2017-01-10 15:30 UTC, duergner commented
@jbellmann are you fine with the changes I did or is there anything else that should be changed? Would like to get it ready for release.

2017-01-10 16:37 UTC, jbellmann commented
👍

2017-01-10 16:38 UTC, duergner commented
👍

2017-01-10 16:38 UTC, merged